#Hugo configuration
title = "Test: First Party Cookies = True"
baseURL = "https:\/\/www.fpctest.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758397"
subfolder = ""
firstpartycookies = true
cookiedomain = "fpctest.com"
